name: coreml27
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.13=py27_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_0
  - openssl=1.0.2p=h1de35cc_0
  - pip=10.0.1=py27_0
  - python=2.7.15=h138c1fe_0
  - readline=7.0=hc1231fa_4
  - setuptools=40.0.0=py27_0
  - sqlite=3.24.0=ha441bb4_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.1=py27_0
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - appnope==0.1.0
    - backports-abc==0.5
    - backports.functools-lru-cache==1.5
    - backports.shutil-get-terminal-size==1.0.0
    - bleach==2.1.4
    - configparser==3.5.0
    - coremltools==2.0b1
    - cycler==0.10.0
    - decorator==4.3.0
    - entrypoints==0.2.3
    - enum34==1.1.6
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - futures==3.2.0
    - h5py==2.7.0
    - html5lib==1.0.1
    - ipaddress==1.0.22
    - ipykernel==4.8.2
    - ipython==5.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.0
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - keras==2.0.8
    - kiwisolver==1.0.1
    - markupsafe==1.0
    - matplotlib==2.2.3
    - mistune==0.8.3
    - mock==2.0.0
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - notebook==5.6.0
    - numpy==1.13.0
    - pandocfilters==1.4.2
    - pathlib2==2.3.2
    - pbr==4.2.0
    - pexpect==4.6.0
    - pickleshare==0.7.4
    - pillow==5.2.0
    - prometheus-client==0.3.1
    - prompt-toolkit==1.0.15
    - protobuf==3.1.0
    - ptyprocess==0.6.0
    - pygments==2.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.7.3
    - pytz==2018.5
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.1
    - scandir==1.9.0
    - scikit-learn==0.17
    - scipy==1.1.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - singledispatch==3.4.0.3
    - six==1.10.0
    - subprocess32==3.5.2
    - tensorflow==1.0.1
    - terminado==0.8.1
    - testpath==0.3.1
    - theano==1.0.2
    - tornado==5.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.0
    - xgboost==0.71
prefix: /anaconda3/envs/coreml27

